import React from 'react'
export const metadata = {
  title: ' maram-tours',
  description: ' Generated by maram-tours',
  icons: {
    icon: '/MARAM-LOGO 1 (1).png',
  },
};

import About from '@/_components/meeta/meeta';

export default function AboutPage() {
  return <About />;
}