
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/_components/navbar/page";
import Footer from "@/_components/footer/page";

import AboutPage from "@/_components/meeta/meeta";



<AboutPage/>




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


// export const metadata = {
//   title: ' maram-tours',
//   description: ' Generated by maram-tours',
//   icons: {
//     icon: '/MARAM-LOGO 1 (1).png',
//   },
// };





export default  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
     
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
            <Navbar/>
            
             <main className="flex-1">
          {children}
        </main>
          <Footer />
      </body>
    
    </html>
  );
}
